# Generated by Django 5.0 on 2023-12-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classification_book_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='book',
            name='classification',
        ),
        migrations.AddField(
            model_name='book',
            name='classification',
            field=models.ManyToManyField(to='api.classification'),
        ),
    ]
