# Generated by Django 5.0 on 2023-12-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_genre_book_genres_remove_book_classification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genres',
            new_name='genre',
        ),
    ]
